version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: warehouse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: warehouse-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin2@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin2
    ports:
      - "5050:80"
    depends_on:
      - postgres

  bot:
    build:
      context: .
    container_name: warehouse-bot
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
      - ./errors:/app/errors
    restart: unless-stopped

volumes:
  pgdata:
